FROM centos:7.1.1503

RUN yum -y install gcc-c++ make ruby-devel \
      && yum clean all \
      && gem install bundler

WORKDIR /usr/local/src

COPY Gemfile ./
COPY fluent-plugin-systemd.gemspec ./
RUN bundle install -j4 -r3
COPY . .
RUN bundle exec rake test
