name: CI

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: ${{ matrix.target.env }}
    strategy:
      matrix:
        target:
          - env: ubuntu
            dockerfile: Dockerfile.ubuntu
          - env: td-agent-deb
            dockerfile: Dockerfile.tdagent-ubuntu
          - env: td-agent-rpm
            dockerfile: Dockerfile.tdagent-almalinux
          - env: ruby32
            dockerfile: Dockerfile.ruby32
          - env: ruby34
            dockerfile: Dockerfile.ruby34
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: test/docker/${{ matrix.target.dockerfile }}
  rubocop:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        run: bundle exec rake rubocop
